In [1]:
import numpy as np

In [23]:
a=np.array([10,20,30,40,50,60])

In [24]:
a

array([10, 20, 30, 40, 50, 60])

In [27]:
a.shape

(6,)

In [28]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [29]:
b.shape

(2, 2)

In [5]:
b

array([[1, 2],
       [3, 4]])

In [34]:
c=b=np.array([[1,2],[3,4],[5,8]])

In [32]:
c.shape

(1, 3, 2)

In [7]:
c

array([[[1, 2],
        [3, 4],
        [5, 8]]])

In [12]:
c.dtype

dtype('int64')

In [17]:
c.size

6

In [21]:
a.shape

(3,)

In [36]:
d=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

In [37]:
d

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [56]:
d.shape

(2, 2, 2)

In [39]:
a.ndim
b.ndim

2

In [44]:
a.itemsize


8

In [43]:
a.nbytes

48

In [47]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [55]:
b[0,1]

np.int64(2)

In [52]:
b[0,7]

IndexError: index 7 is out of bounds for axis 1 with size 2

In [59]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [61]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [62]:
np.full((2,3),3)

array([[3, 3, 3],
       [3, 3, 3]])

In [63]:
z=np.array([[6,7],[5,4]])
z

array([[6, 7],
       [5, 4]])

In [99]:
a


array([10, 20, 30, 40, 50, 60])

In [106]:
b

array([[1, 2],
       [3, 4],
       [5, 8]])

In [107]:
b.T

array([[1, 3, 5],
       [2, 4, 8]])

In [109]:
e=np.array([20,48,56])
f=np.array([23,76,40])

In [110]:
e+f

array([ 43, 124,  96])

In [111]:
e*f

array([ 460, 3648, 2240])

In [112]:
e**f

array([-6522549266571853824,                    0,                    0])

In [113]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [114]:
import pandas as pd

In [ ]:
df=pd.Series([10,20,30])
df

0    10
1    20
2    30
dtype: int64

In [134]:
s={
    "name":["snehal","gdhwgd","bfjenf"],
    "age":[22,None,44] 
}



In [137]:
df=pd.DataFrame(s)
df

,name,age
0,snehal,22.0
1,gdhwgd,NaN
2,bfjenf,44.0


In [138]:
num=df["age"].to_numpy()
num

array([22., nan, 44.])

In [143]:
np.nan_to_num(df["age"],nan=0)

array([22.,  0., 44.])